= Flags
:toc:

The following flags are available to customise Goplum's behaviour. They can be
either passed on the command-line, or set as environment variables.

== api-port

[source,shell script]
----
# Command line
goplum --api-port 1234

# Environment variable
API_PORT=1234 goplum
----

Sets the port that GoPlum will listen on for API clients.

For more information on the GoPlum API see the link:api.adoc[API documentation].

Default: `7586`.

== ca-cert, cert and key

[source,shell script]
----
# Command line
goplum --ca-cert /etc/ssl/authority.crt \
  --cert /home/goplum/server.crt \
  --key /home/goplum/server.key

# Environment variable
CA_CERT=/etc/ssl/authority.crt \
CERT=/home/goplum/server.crt \
KEY=/home/goplum/server.key goplum
----

Sets the path for the certificate authority's public certificate, GoPlum's public
certificate, and GoPlum's private key, for use with the GoPlum API.

For information on how to generate these see the link:api.adoc[API documentation].

Defaults: `ca.crt`, `goplum.crt` and `goplum.key`, respectively.

Note: if all three files are not found, GoPlum's API will not be enabled.

== config

[source,shell script]
----
# Command line
goplum -config /etc/goplum.conf

# Environment variable
CONFIG=/etc/goplum.conf goplum
----

Sets the path to Goplum's configuration file.

If the path is relative it is interpreted with respect to Goplum's working directory.

Default: `goplum.conf`.

== plugins

[source,shell script]
----
# Command line
goplum -plugins /path/to/plugins/**.so

# Environment variable
PLUGINS=/path/to/plugins/**.so goplum
----

Sets the glob pattern that Goplum will use to find plugins. The glob pattern can contain
the following special terms:

[cols="1,4"]
|==============================================================================
|Term | Meaning

|`*`
|Matches any sequence of non-path-separators

|`**`
|Matches any sequence of characters, including path separators

|`?`
|Matches any single non-path-separator character

|`[class]`
|Matches any single non-path-separator from the class of characters
 (e.g. `[abc]`, `[a-z]`, or `[^def]`).

|`{a,b,...}`
|Matches a sequence of characters if one of the comma-separated alternatives match
|==============================================================================

These special terms can be escaped with a backslash.

If the path is relative it is interpreted with respect to Goplum's working directory.

Default: `plugins/**.so`.

== quiet

[source,shell script]
----
# Command line
goplum -quiet

# Environment variable
QUIET=true goplum
----

Reduces the amount of logging from normal operations, such as checks being
executed.

Default: `false`

== tombstone

[source,shell script]
----
# Command line
goplum -tombstone /var/run/goplum.tomb

# Environment variable
TOMBSTONE=/var/run/goplum.tomb goplum
----

The path to save and load Goplum's "tombstone" data. This is data saved when Goplum is
shutting down, and reloaded if it starts up again within a short period of time.

Goplum can operate without a tombstone file, and will run even if it can't read or
write to the specified file, but the status of checks will be lost when it is restarted.

Default: `/tmp/goplum.tomb`
