// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: goplum.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_INDETERMINATE Status = 0
	Status_GOOD          Status = 1
	Status_FAILING       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "INDETERMINATE",
		1: "GOOD",
		2: "FAILING",
	}
	Status_value = map[string]int32{
		"INDETERMINATE": 0,
		"GOOD":          1,
		"FAILING":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_goplum_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_goplum_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{0}
}

type CheckName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckName) Reset() {
	*x = CheckName{}
	mi := &file_goplum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckName) ProtoMessage() {}

func (x *CheckName) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckName.ProtoReflect.Descriptor instead.
func (*CheckName) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{0}
}

func (x *CheckName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*Check               `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckList) Reset() {
	*x = CheckList{}
	mi := &file_goplum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckList) ProtoMessage() {}

func (x *CheckList) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckList.ProtoReflect.Descriptor instead.
func (*CheckList) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{1}
}

func (x *CheckList) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	LastRun       int64                  `protobuf:"varint,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	Settled       bool                   `protobuf:"varint,4,opt,name=settled,proto3" json:"settled,omitempty"`
	State         Status                 `protobuf:"varint,5,opt,name=state,proto3,enum=api.Status" json:"state,omitempty"`
	Suspended     bool                   `protobuf:"varint,6,opt,name=suspended,proto3" json:"suspended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_goplum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{2}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Check) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *Check) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *Check) GetState() Status {
	if x != nil {
		return x.State
	}
	return Status_INDETERMINATE
}

func (x *Check) GetSuspended() bool {
	if x != nil {
		return x.Suspended
	}
	return false
}

type Fact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Fact_Int
	//	*Fact_Str
	Value         isFact_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_goplum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{3}
}

func (x *Fact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fact) GetValue() isFact_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Fact) GetInt() int64 {
	if x != nil {
		if x, ok := x.Value.(*Fact_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Fact) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Fact_Str); ok {
			return x.Str
		}
	}
	return ""
}

type isFact_Value interface {
	isFact_Value()
}

type Fact_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Fact_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

func (*Fact_Int) isFact_Value() {}

func (*Fact_Str) isFact_Value() {}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         string                 `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Result        Status                 `protobuf:"varint,3,opt,name=result,proto3,enum=api.Status" json:"result,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Facts         []*Fact                `protobuf:"bytes,5,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_goplum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *Result) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Result) GetResult() Status {
	if x != nil {
		return x.Result
	}
	return Status_INDETERMINATE
}

func (x *Result) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Result) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_goplum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{5}
}

var File_goplum_proto protoreflect.FileDescriptor

const file_goplum_proto_rawDesc = "" +
	"\n" +
	"\fgoplum.proto\x12\x03api\"\x1f\n" +
	"\tCheckName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\tCheckList\x12\"\n" +
	"\x06checks\x18\x01 \x03(\v2\n" +
	".api.CheckR\x06checks\"\xa5\x01\n" +
	"\x05Check\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\blast_run\x18\x03 \x01(\x03R\alastRun\x12\x18\n" +
	"\asettled\x18\x04 \x01(\bR\asettled\x12!\n" +
	"\x05state\x18\x05 \x01(\x0e2\v.api.StatusR\x05state\x12\x1c\n" +
	"\tsuspended\x18\x06 \x01(\bR\tsuspended\"K\n" +
	"\x04Fact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x03H\x00R\x03int\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03strB\a\n" +
	"\x05value\"\x90\x01\n" +
	"\x06Result\x12\x14\n" +
	"\x05check\x18\x01 \x01(\tR\x05check\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12#\n" +
	"\x06result\x18\x03 \x01(\x0e2\v.api.StatusR\x06result\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1f\n" +
	"\x05facts\x18\x05 \x03(\v2\t.api.FactR\x05facts\"\a\n" +
	"\x05Empty*2\n" +
	"\x06Status\x12\x11\n" +
	"\rINDETERMINATE\x10\x00\x12\b\n" +
	"\x04GOOD\x10\x01\x12\v\n" +
	"\aFAILING\x10\x022\xd6\x01\n" +
	"\x06GoPlum\x12$\n" +
	"\aResults\x12\n" +
	".api.Empty\x1a\v.api.Result0\x01\x12'\n" +
	"\tGetChecks\x12\n" +
	".api.Empty\x1a\x0e.api.CheckList\x12&\n" +
	"\bGetCheck\x12\x0e.api.CheckName\x1a\n" +
	".api.Check\x12*\n" +
	"\fSuspendCheck\x12\x0e.api.CheckName\x1a\n" +
	".api.Check\x12)\n" +
	"\vResumeCheck\x12\x0e.api.CheckName\x1a\n" +
	".api.CheckB\x18Z\x16chameth.com/goplum/apib\x06proto3"

var (
	file_goplum_proto_rawDescOnce sync.Once
	file_goplum_proto_rawDescData []byte
)

func file_goplum_proto_rawDescGZIP() []byte {
	file_goplum_proto_rawDescOnce.Do(func() {
		file_goplum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goplum_proto_rawDesc), len(file_goplum_proto_rawDesc)))
	})
	return file_goplum_proto_rawDescData
}

var file_goplum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goplum_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_goplum_proto_goTypes = []any{
	(Status)(0),       // 0: api.Status
	(*CheckName)(nil), // 1: api.CheckName
	(*CheckList)(nil), // 2: api.CheckList
	(*Check)(nil),     // 3: api.Check
	(*Fact)(nil),      // 4: api.Fact
	(*Result)(nil),    // 5: api.Result
	(*Empty)(nil),     // 6: api.Empty
}
var file_goplum_proto_depIdxs = []int32{
	3, // 0: api.CheckList.checks:type_name -> api.Check
	0, // 1: api.Check.state:type_name -> api.Status
	0, // 2: api.Result.result:type_name -> api.Status
	4, // 3: api.Result.facts:type_name -> api.Fact
	6, // 4: api.GoPlum.Results:input_type -> api.Empty
	6, // 5: api.GoPlum.GetChecks:input_type -> api.Empty
	1, // 6: api.GoPlum.GetCheck:input_type -> api.CheckName
	1, // 7: api.GoPlum.SuspendCheck:input_type -> api.CheckName
	1, // 8: api.GoPlum.ResumeCheck:input_type -> api.CheckName
	5, // 9: api.GoPlum.Results:output_type -> api.Result
	2, // 10: api.GoPlum.GetChecks:output_type -> api.CheckList
	3, // 11: api.GoPlum.GetCheck:output_type -> api.Check
	3, // 12: api.GoPlum.SuspendCheck:output_type -> api.Check
	3, // 13: api.GoPlum.ResumeCheck:output_type -> api.Check
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_goplum_proto_init() }
func file_goplum_proto_init() {
	if File_goplum_proto != nil {
		return
	}
	file_goplum_proto_msgTypes[3].OneofWrappers = []any{
		(*Fact_Int)(nil),
		(*Fact_Str)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goplum_proto_rawDesc), len(file_goplum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goplum_proto_goTypes,
		DependencyIndexes: file_goplum_proto_depIdxs,
		EnumInfos:         file_goplum_proto_enumTypes,
		MessageInfos:      file_goplum_proto_msgTypes,
	}.Build()
	File_goplum_proto = out.File
	file_goplum_proto_goTypes = nil
	file_goplum_proto_depIdxs = nil
}
