// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: goplum.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_INDETERMINATE Status = 0
	Status_GOOD          Status = 1
	Status_FAILING       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "INDETERMINATE",
		1: "GOOD",
		2: "FAILING",
	}
	Status_value = map[string]int32{
		"INDETERMINATE": 0,
		"GOOD":          1,
		"FAILING":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_goplum_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_goplum_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{0}
}

type CheckName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CheckName) Reset() {
	*x = CheckName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckName) ProtoMessage() {}

func (x *CheckName) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckName.ProtoReflect.Descriptor instead.
func (*CheckName) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{0}
}

func (x *CheckName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checks []*Check `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *CheckList) Reset() {
	*x = CheckList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckList) ProtoMessage() {}

func (x *CheckList) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckList.ProtoReflect.Descriptor instead.
func (*CheckList) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{1}
}

func (x *CheckList) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

type Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	LastRun   int64  `protobuf:"varint,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	Settled   bool   `protobuf:"varint,4,opt,name=settled,proto3" json:"settled,omitempty"`
	State     Status `protobuf:"varint,5,opt,name=state,proto3,enum=api.Status" json:"state,omitempty"`
	Suspended bool   `protobuf:"varint,6,opt,name=suspended,proto3" json:"suspended,omitempty"`
}

func (x *Check) Reset() {
	*x = Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{2}
}

func (x *Check) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Check) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Check) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *Check) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *Check) GetState() Status {
	if x != nil {
		return x.State
	}
	return Status_INDETERMINATE
}

func (x *Check) GetSuspended() bool {
	if x != nil {
		return x.Suspended
	}
	return false
}

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*Fact_Int
	//	*Fact_Str
	Value isFact_Value `protobuf_oneof:"value"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{3}
}

func (x *Fact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Fact) GetValue() isFact_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Fact) GetInt() int64 {
	if x, ok := x.GetValue().(*Fact_Int); ok {
		return x.Int
	}
	return 0
}

func (x *Fact) GetStr() string {
	if x, ok := x.GetValue().(*Fact_Str); ok {
		return x.Str
	}
	return ""
}

type isFact_Value interface {
	isFact_Value()
}

type Fact_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Fact_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

func (*Fact_Int) isFact_Value() {}

func (*Fact_Str) isFact_Value() {}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check  string  `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	Time   int64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Result Status  `protobuf:"varint,3,opt,name=result,proto3,enum=api.Status" json:"result,omitempty"`
	Detail string  `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Facts  []*Fact `protobuf:"bytes,5,rep,name=facts,proto3" json:"facts,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *Result) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Result) GetResult() Status {
	if x != nil {
		return x.Result
	}
	return Status_INDETERMINATE
}

func (x *Result) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Result) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goplum_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_goplum_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_goplum_proto_rawDescGZIP(), []int{5}
}

var File_goplum_proto protoreflect.FileDescriptor

var file_goplum_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x70, 0x6c, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x61, 0x70, 0x69, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x06, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x73, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x72, 0x75, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x52,
	0x75, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x22, 0x4b, 0x0a,
	0x04, 0x46, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x03, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x05,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x52, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x44, 0x45, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54,
	0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x41, 0x49, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x32, 0xd6, 0x01, 0x0a, 0x06, 0x47,
	0x6f, 0x50, 0x6c, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x12, 0x27, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x0c,
	0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x73, 0x6d, 0x69, 0x74, 0x68, 0x2f, 0x67, 0x6f, 0x70, 0x6c, 0x75, 0x6d, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goplum_proto_rawDescOnce sync.Once
	file_goplum_proto_rawDescData = file_goplum_proto_rawDesc
)

func file_goplum_proto_rawDescGZIP() []byte {
	file_goplum_proto_rawDescOnce.Do(func() {
		file_goplum_proto_rawDescData = protoimpl.X.CompressGZIP(file_goplum_proto_rawDescData)
	})
	return file_goplum_proto_rawDescData
}

var file_goplum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goplum_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_goplum_proto_goTypes = []interface{}{
	(Status)(0),       // 0: api.Status
	(*CheckName)(nil), // 1: api.CheckName
	(*CheckList)(nil), // 2: api.CheckList
	(*Check)(nil),     // 3: api.Check
	(*Fact)(nil),      // 4: api.Fact
	(*Result)(nil),    // 5: api.Result
	(*Empty)(nil),     // 6: api.Empty
}
var file_goplum_proto_depIdxs = []int32{
	3, // 0: api.CheckList.checks:type_name -> api.Check
	0, // 1: api.Check.state:type_name -> api.Status
	0, // 2: api.Result.result:type_name -> api.Status
	4, // 3: api.Result.facts:type_name -> api.Fact
	6, // 4: api.GoPlum.Results:input_type -> api.Empty
	6, // 5: api.GoPlum.GetChecks:input_type -> api.Empty
	1, // 6: api.GoPlum.GetCheck:input_type -> api.CheckName
	1, // 7: api.GoPlum.SuspendCheck:input_type -> api.CheckName
	1, // 8: api.GoPlum.ResumeCheck:input_type -> api.CheckName
	5, // 9: api.GoPlum.Results:output_type -> api.Result
	2, // 10: api.GoPlum.GetChecks:output_type -> api.CheckList
	3, // 11: api.GoPlum.GetCheck:output_type -> api.Check
	3, // 12: api.GoPlum.SuspendCheck:output_type -> api.Check
	3, // 13: api.GoPlum.ResumeCheck:output_type -> api.Check
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_goplum_proto_init() }
func file_goplum_proto_init() {
	if File_goplum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goplum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goplum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goplum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goplum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goplum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goplum_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_goplum_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Fact_Int)(nil),
		(*Fact_Str)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goplum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goplum_proto_goTypes,
		DependencyIndexes: file_goplum_proto_depIdxs,
		EnumInfos:         file_goplum_proto_enumTypes,
		MessageInfos:      file_goplum_proto_msgTypes,
	}.Build()
	File_goplum_proto = out.File
	file_goplum_proto_rawDesc = nil
	file_goplum_proto_goTypes = nil
	file_goplum_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoPlumClient is the client API for GoPlum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoPlumClient interface {
	Results(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GoPlum_ResultsClient, error)
	GetChecks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckList, error)
	GetCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error)
	SuspendCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error)
	ResumeCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error)
}

type goPlumClient struct {
	cc grpc.ClientConnInterface
}

func NewGoPlumClient(cc grpc.ClientConnInterface) GoPlumClient {
	return &goPlumClient{cc}
}

func (c *goPlumClient) Results(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GoPlum_ResultsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GoPlum_serviceDesc.Streams[0], "/api.GoPlum/Results", opts...)
	if err != nil {
		return nil, err
	}
	x := &goPlumResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoPlum_ResultsClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type goPlumResultsClient struct {
	grpc.ClientStream
}

func (x *goPlumResultsClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goPlumClient) GetChecks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CheckList, error) {
	out := new(CheckList)
	err := c.cc.Invoke(ctx, "/api.GoPlum/GetChecks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPlumClient) GetCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error) {
	out := new(Check)
	err := c.cc.Invoke(ctx, "/api.GoPlum/GetCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPlumClient) SuspendCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error) {
	out := new(Check)
	err := c.cc.Invoke(ctx, "/api.GoPlum/SuspendCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPlumClient) ResumeCheck(ctx context.Context, in *CheckName, opts ...grpc.CallOption) (*Check, error) {
	out := new(Check)
	err := c.cc.Invoke(ctx, "/api.GoPlum/ResumeCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoPlumServer is the server API for GoPlum service.
type GoPlumServer interface {
	Results(*Empty, GoPlum_ResultsServer) error
	GetChecks(context.Context, *Empty) (*CheckList, error)
	GetCheck(context.Context, *CheckName) (*Check, error)
	SuspendCheck(context.Context, *CheckName) (*Check, error)
	ResumeCheck(context.Context, *CheckName) (*Check, error)
}

// UnimplementedGoPlumServer can be embedded to have forward compatible implementations.
type UnimplementedGoPlumServer struct {
}

func (*UnimplementedGoPlumServer) Results(*Empty, GoPlum_ResultsServer) error {
	return status.Errorf(codes.Unimplemented, "method Results not implemented")
}
func (*UnimplementedGoPlumServer) GetChecks(context.Context, *Empty) (*CheckList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChecks not implemented")
}
func (*UnimplementedGoPlumServer) GetCheck(context.Context, *CheckName) (*Check, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheck not implemented")
}
func (*UnimplementedGoPlumServer) SuspendCheck(context.Context, *CheckName) (*Check, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendCheck not implemented")
}
func (*UnimplementedGoPlumServer) ResumeCheck(context.Context, *CheckName) (*Check, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeCheck not implemented")
}

func RegisterGoPlumServer(s *grpc.Server, srv GoPlumServer) {
	s.RegisterService(&_GoPlum_serviceDesc, srv)
}

func _GoPlum_Results_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoPlumServer).Results(m, &goPlumResultsServer{stream})
}

type GoPlum_ResultsServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type goPlumResultsServer struct {
	grpc.ServerStream
}

func (x *goPlumResultsServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _GoPlum_GetChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPlumServer).GetChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoPlum/GetChecks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPlumServer).GetChecks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPlum_GetCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPlumServer).GetCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoPlum/GetCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPlumServer).GetCheck(ctx, req.(*CheckName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPlum_SuspendCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPlumServer).SuspendCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoPlum/SuspendCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPlumServer).SuspendCheck(ctx, req.(*CheckName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPlum_ResumeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPlumServer).ResumeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GoPlum/ResumeCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPlumServer).ResumeCheck(ctx, req.(*CheckName))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoPlum_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GoPlum",
	HandlerType: (*GoPlumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChecks",
			Handler:    _GoPlum_GetChecks_Handler,
		},
		{
			MethodName: "GetCheck",
			Handler:    _GoPlum_GetCheck_Handler,
		},
		{
			MethodName: "SuspendCheck",
			Handler:    _GoPlum_SuspendCheck_Handler,
		},
		{
			MethodName: "ResumeCheck",
			Handler:    _GoPlum_ResumeCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Results",
			Handler:       _GoPlum_Results_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goplum.proto",
}
